version: 1.0.{build}
image:
  - Ubuntu

configuration:
  - BuildCmd
  - DeleteCmd
  - DeployCmd
  - InitCmd
  - LocalCmd
  - PackageCmd
  - PipelineCmd
  - PublishCmd
  - SyncCmd
  - TelemetryCmd
  - ValidateCmd
  - RestOfThem

environment:
  AWS_DEFAULT_REGION: us-east-1
  AWS_REGION: us-east-1
  SAM_CLI_DEV: 1

  matrix:

    - PYTHON_HOME: "C:\\Python37-x64"
      PYTHON_VERSION: '3.7'
      PYTHON_ARCH: '64'
      RUN_SMOKE: 1
      NOSE_PARAMETERIZED_NO_WARN: 1
      INSTALL_PY_36_PIP: 1
      INSTALL_PY_38_PIP: 1
      INSTALL_PY_39_PIP: 1
      AWS_S3: 'AWS_S3_37'
      AWS_ECR: 'AWS_ECR_37'
      APPVEYOR_CONSOLE_DISABLE_PTY: true

#    - PYTHON_HOME: "C:\\Python38-x64"
#      PYTHON_VERSION: '3.8'
#      PYTHON_ARCH: '64'
#      RUN_SMOKE: 1
#      NOSE_PARAMETERIZED_NO_WARN: 1
#      INSTALL_PY_36_PIP: 1
#      INSTALL_PY_37_PIP: 1
#      INSTALL_PY_39_PIP: 1
#      AWS_S3: 'AWS_S3_38'
#      AWS_ECR: 'AWS_ECR_38'
#      APPVEYOR_CONSOLE_DISABLE_PTY: true
#
#    - PYTHON_HOME: "C:\\Python39-x64"
#      PYTHON_VERSION: '3.9'
#      PYTHON_ARCH: '64'
#      RUN_SMOKE: 1
#      NOSE_PARAMETERIZED_NO_WARN: 1
#      INSTALL_PY_36_PIP: 1
#      INSTALL_PY_37_PIP: 1
#      INSTALL_PY_38_PIP: 1
#      AWS_S3: 'AWS_S3_39'
#      AWS_ECR: 'AWS_ECR_39'
#      APPVEYOR_CONSOLE_DISABLE_PTY: true

install:
  # apt repo for python3.9 installation
  - sh: "sudo add-apt-repository ppa:deadsnakes/ppa"
  # AppVeyor's apt-get cache might be outdated, and the package could potentially be 404.
  - sh: "sudo apt-get update"

  - sh: "gvm use go1.13"
  - sh: "echo $PATH"
  - sh: "ls /usr/"
  - sh: "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
  - sh: "PATH=$JAVA_HOME/bin:$PATH"
  - sh: "source ${HOME}/venv${PYTHON_VERSION}/bin/activate"
  - sh: "rvm use 2.7.2"
  - sh: "docker --version"

  # Install latest gradle
  - sh: "sudo apt-get -y remove gradle"
  - sh: "wget https://services.gradle.org/distributions/gradle-5.5-bin.zip -P /tmp"
  - sh: "sudo unzip -d /opt/gradle /tmp/gradle-*.zip"
  - sh: "PATH=/opt/gradle/gradle-5.5/bin:$PATH"

  # Install AWS CLI
  - sh: "virtualenv aws_cli"
  - sh: "./aws_cli/bin/python -m pip install awscli"
  - sh: "PATH=$(echo $PWD'/aws_cli/bin'):$PATH"

  - sh: "sudo apt-get -y install python3.6"
  - sh: "sudo apt-get -y install python2.7"
  - sh: "sudo apt-get -y install python3.7"
  - sh: "sudo apt-get -y install python3.8"
  - sh: "sudo apt-get -y install python3.9"

  - sh: "which python3.8"
  - sh: "which python3.7"
  - sh: "which python3.6"
  - sh: "which python3.9"
  - sh: "which python2.7"

  - sh: "PATH=$PATH:/usr/bin/python3.9:/usr/bin/python3.8:/usr/bin/python3.7"
  - sh: "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py"

  - sh: "sudo apt-get -y install python3-distutils"
  - sh: "sudo apt-get -y install python3.9-distutils"
  - ps: "If ($env:INSTALL_PY_39_PIP) {python3.9 get-pip.py --user}"
  - ps: "If ($env:INSTALL_PY_38_PIP) {python3.8 get-pip.py --user}"
  - ps: "If ($env:INSTALL_PY_37_PIP) {python3.7 get-pip.py --user}"
  - ps: "If ($env:INSTALL_PY_36_PIP) {python3.6 get-pip.py --user}"

  # required for RIE with arm64 in linux
  - sh: "docker run --rm --privileged multiarch/qemu-user-static --reset -p yes"

  # update ca-certificates which causes failures with newest golang library
  - sh: "sudo apt-get install --reinstall ca-certificates"

  # increase re-tries for boto3 clients
  - sh: "mkdir ~/.aws"
  - sh: "echo '[default]\nmax_attempts = 40\n' >> ~/.aws/config"

build_script:
  - "python -c \"import sys; print(sys.executable)\""
  - sh: "
    if [[ -n $BY_CANARY ]];
      then echo Logging in Public ECR; aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws;
    fi"

for:

  - matrix:
      only:
        - configuration: BuildCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv -n 4 tests/integration/buildcmd/"

  - matrix:
      only:
        - configuration: DeleteCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv tests/integration/delete/"

  - matrix:
      only:
        - configuration: DeployCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv -n 4 tests/integration/deploy/"

  - matrix:
      only:
        - configuration: InitCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv tests/integration/init/"


  - matrix:
      only:
        - configuration: LocalCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv tests/integration/local/"

  - matrix:
      only:
        - configuration: PackageCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv tests/integration/package/"

  - matrix:
      only:
        - configuration: PipelineCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv tests/integration/pipeline/"

  - matrix:
      only:
        - configuration: PublishCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv tests/integration/publish/"

  - matrix:
      only:
        - configuration: SyncCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv -n 4 tests/integration/sync/"

  - matrix:
      only:
        - configuration: TelemetryCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv tests/integration/telemetry/"

  - matrix:
      only:
        - configuration: ValidateCmd

    test_script:
      - "pip install -e \".[dev]\""
      - sh: "pytest -vv tests/integration/validate/"


  - matrix:
      only:
        - configuration: RestOfThem

    test_script:
      - # Pre-dev Tests
      - "pip install -e \".[pre-dev]\""
      - "pylint --rcfile .pylintrc samcli"

      # Dev Tests
      - "pip install -e \".[dev]\""
      - "pytest --cov samcli --cov-report term-missing --cov-fail-under 94 tests/unit"
      - "pylint --rcfile .pylintrc samcli"
      - "mypy setup.py samcli tests"
      - "black --check setup.py tests samcli"
      - "pytest -n 4 tests/functional"
      - "pytest -vv tests/regression"
      - ps: "If ($env:RUN_SMOKE) {pytest -n 4 -vv tests/smoke}"
      # Set JAVA_HOME to java11
      - sh: "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
      - sh: "pytest -vv tests/integration/buildcmd/test_build_cmd.py -k test_building_java11_in_process"
